apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-lab-deployment
  labels:
    app: final-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-lab
  template:
    metadata:
      labels:
        app: final-lab
    spec:
      containers:
      - name: final-lab
        image: mfigueroah/final-lab:latest
        ports:
        - containerPort: 8080


apiVersion: v1
kind: Service
metadata:
  name: final-lab
spec:
  selector:
    app: final-lab
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 8080  
  type: LoadBalancer  
