name: CI

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Descarga repositorio
        uses: actions/checkout@v3

      - name: Build      
        run: |
          chmod +x gradlew
          ./gradlew build
          ./gradlew bootJar --debug
          ls -ltrh build/libs
          
                
        
