name: CI

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Descarga repositorio
        uses: actions/checkout@v3

      - name: Añadir carpeta y realizar commit
        run: |
          mkdir gradle/wrapper
          git add  gradle/wrapper
          git commit -m "Añadir nueva-carpeta" || true
          git push
                
        
