name: CI

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Descarga repositorio
        uses: actions/checkout@v3


  test:
    
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        
      - name: Install dependencies
        run: npm install
   
      - name: Build project
        run: npm run build
        
      - name: Testing
        run: npm run test
  #test:
  
    #needs: build
    #runs-on: ubuntu-latest
    #steps: 
                
    #- name: Descarga repositorio
    #  uses: actions/checkout@v3
        
    #- name: SAST (Static Application Security Testing)     
    #  run: |
    #    chmod +x gradlew
    #    ./gradlew build sonar -Dsonar.token=${{secrets.SONAR_TOKEN}}
          
                
        
