name: CI

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Descarga repositorio
        uses: actions/checkout@v3
  
  test:
  
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: TypeScript Build 
      uses: alexthemaster/action-build-typescript@v1.3.1
                
    - name: Descarga repositorio
      uses: actions/checkout@v3
        
    - name: SAST (Static Application Security Testing)     
      run: |
        chmod +x gradlew
        ./gradlew build sonar -Dsonar.token=${{secrets.SONAR_TOKEN}}
          
                
        
