name: CI

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Descarga repositorio
        uses: actions/checkout@v3
       
      - name: Compilacion JAVA
        run: |
          uses: git add build.gradle
          git commit -m "Agregar archivo build.gradle"
          git push
          chmod +x gradlew
          ./gradlew build
                
        
