name: CI

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Descarga repositorio
        uses: actions/checkout@v3

      - name: Create and Add Folder
        run: |
          mkdir gradle
          echo "# Contenido de la carpeta" > gradle/README.md
          git add gradle
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "gradle" || true
          git push
          
                
        
