name: CI

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Descarga repositorio
        uses: actions/checkout@v3
 
  test:
  
    needs: build
    runs-on: ubuntu-latest
    steps: 
                
    - name: Descarga repositorio
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4.0.0
      with:
          java-version: 17
          distribution: 'temurin'
     
    - name: Build      
      run: |
          chmod +x gradlew
          ./gradlew build
          ls -ltrh build/libs  
          
    - name: SAST (Static Application Security Testing)     
      run: |
        chmod +x gradlew
        ./gradlew build sonar -Dsonar.token=${{secrets.SONAR_TOKEN}}
        
        
          
                
        
